# Generated by Django 5.1.3 on 2024-12-01 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Headings',
            fields=[
                ('headingsID', models.AutoField(primary_key=True, serialize=False)),
                ('headingName', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='MainCategory',
            fields=[
                ('categoryID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('manufacturerID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='HeadingsDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generalInfo', models.TextField()),
                ('DetailedInfo', models.TextField()),
                ('heading', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='material.headings')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='heading_details', to='material.maincategory')),
            ],
        ),
        migrations.CreateModel(
            name='CategoryImage',
            fields=[
                ('imageID', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='category_images/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='material.maincategory')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('productID', models.AutoField(primary_key=True, serialize=False)),
                ('Type', models.CharField(max_length=255)),
                ('Kurztext', models.CharField(max_length=255)),
                ('Langtext', models.TextField()),
                ('BestellnummerHersteller', models.CharField(max_length=255)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='material.maincategory')),
            ],
        ),
        migrations.CreateModel(
            name='ProductManufacturer',
            fields=[
                ('tableID', models.AutoField(primary_key=True, serialize=False)),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manufacturer_products', to='material.manufacturer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_manufacturers', to='material.product')),
            ],
        ),
    ]
