# Generated by Django 4.2.5 on 2024-12-16 01:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryPDF',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pdf_type', models.CharField(choices=[('manual', 'Manual'), ('specs', 'Specifications'), ('guide', 'User Guide'), ('other', 'Other')], max_length=50)),
                ('pdf_file', models.FileField(upload_to='category_pdfs/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pdfs', to='material.maincategory')),
            ],
        ),
    ]
