# Generated by Django 4.2.5 on 2024-12-16 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0002_categorypdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorypdf',
            name='pdf_type',
            field=models.CharField(choices=[('datenblatter', 'Datenblatter'), ('montageanleitung', 'Montageanleitung'), ('prufzertifikate', 'Prufzertifikate'), ('sonstiges', 'Sonstiges')], max_length=50),
        ),
    ]
